let products = [
  {
    id: 1,
    name: "Arna",
    price: 500,
    category: "BEER",
    image: "img/Beer/arna.png",
    flash: false,
    discount: 0,
  },
  {
    id: 2,
    name: "Barahsinghe",
    price: 400,
    category: "BEER",
    image: "img/Beer/barahsinghe.png",
    flash: false,
    discount: 0,
  },
  {
    id: 3,
    name: "Budweiser",
    price: 390,
    category: "BEER",
    image: "img/Beer/budweiser.png",
    flash: false,
    discount: 0,
  },
  {
    id: 4,
    name: "Carlsberg",
    price: 450,
    category: "BEER",
    image: "img/Beer/carlsberg.png",
    flash: false,
    discount: 0,
  },
  {
    id: 5,
    name: "Gorkha",
    price: 350,
    category: "BEER",
    image: "img/Beer/gorkha.png",
    flash: false,
    discount: 0,
  },
  {
    id: 6,
    name: "Mustang",
    price: 290,
    category: "BEER",
    image: "img/Beer/mustang.png",
    flash: true,
    discount: 5,
  },
  {
    id: 7,
    name: "Nepal Ice",
    price: 300,
    category: "BEER",
    image: "img/Beer/nepalice.png",
    flash: true,
    discount: 5,
  },
  {
    id: 8,
    name: "Tuborg",
    price: 400,
    category: "BEER",
    image: "img/Beer/tuborg.png",
    flash: false,
    discount: 0,
  },
  {
    id: 9,
    name: "Black Label 1L",
    price: 8600,
    category: "WHISKY",
    image: "img/Whisky/Black-level.png",
    flash: false,
    discount: 10,
  },
  {
    id: 10,
    name: "Blue Label 1L",
    price: 64000,
    category: "WHISKY",
    image: "img/Whisky/bluelevel.png",
    flash: true,
    discount: 10,
  },
  {
    id: 11,
    name: "Jack Daniel 1L",
    price: 8300,
    category: "WHISKY",
    image: "img/Whisky/jack.png",
    flash: true,
    discount: 10,
  },
  {
    id: 12,
    name: "Khukuri Rum",
    price: 2450,
    category: "WHISKY",
    image: "img/Whisky/Khukuri.png",
    flash: false,
    discount: 0,
  },
  {
    id: 13,
    name: "Old Durbar Black 1L",
    price: 4395,
    category: "WHISKY",
    image: "img/Whisky/Old-durbar.png",
    flash: false,
    discount: 0,
  },
  {
    id: 14,
    name: "Red Label 1L",
    price: 7000,
    category: "WHISKY",
    image: "img/Whisky/Red-level.png",
    flash: true,
    discount: 10,
  },
  {
    id: 15,
    name: "Royal Stag",
    price: 1800,
    category: "WHISKY",
    image: "img/Whisky/Royal-stag.png",
    flash: false,
    discount: 0,
  },
  {
    id: 16,
    name: "Signature",
    price: 2500,
    category: "WHISKY",
    image: "img/Whisky/Signature.png",
    flash: false,
    discount: 0,
  },
  {
    id: 17,
    name: "Vat 69 1L",
    price: 6400,
    category: "WHISKY",
    image: "img/Whisky/Vat69.png",
    flash: true,
    discount: 10,
  },
  {
    id: 18,
    name: "Big Master",
    price: 850,
    category: "WINE",
    image: "img/Wine/Big-Master.png",
    flash: false,
    discount: 50,
  },
  {
    id: 19,
    name: "Divine Wine",
    price: 750,
    category: "WINE",
    image: "img/Wine/Divine-wine.png",
    flash: false,
    discount: 50,
  },
  {
    id: 20,
    name: "Red Wine",
    price: 770,
    category: "WINE",
    image: "img/Wine/Red-wine.png",
    flash: true,
    discount: 50,
  },
  {
    id: 21,
    name: "Vardys",
    price: 1750,
    category: "WINE",
    image: "img/Wine/Vardys.png",
    flash: false,
    discount: 50,
  },
  {
    id: 22,
    name: "Blue Moon",
    price: 4000,
    category: "BEER",
    image: "img/Beer/bluemoon.png",
    flash: false,
    discount: 5,
  },
  {
    id: 23,
    name: "Brooklyn",
    price: 500,
    category: "BEER",
    image: "img/Beer/brooklyn.png",
    flash: true,
    discount: 5,
  },
  {
    id: 24,
    name: "Everest",
    price: 300,
    category: "BEER",
    image: "img/Beer/everest.png",
    flash: false,
    discount: 5,
  },
  {
    id: 25,
    name: "Heineken",
    price: 400,
    category: "BEER",
    image: "img/Beer/heineken.png",
    flash: false,
    discount: 5,
  },
  {
    id: 26,
    name: "King Fisher",
    price: 300,
    category: "BEER",
    image: "img/Beer/kingfisher.png",
    flash: true,
    discount: 5,
  },
  {
    id: 27,
    name: "Chivas 1L",
    price: 9100,
    category: "WHISKY",
    image: "img/Whisky/chivas.png",
    flash: true,
    discount: 10,
  },
  {
    id: 28,
    name: "Glendfiddich 1L",
    price: 15000,
    category: "WHISKY",
    image: "img/Whisky/glenfiddich.png",
    flash: false,
    discount: 10,
  },
  {
    id: 29,
    name: "Jameson",
    price: 6000,
    category: "WHISKY",
    image: "img/Whisky/jameson.png",
    flash: false,
    discount: 10,
  },
  {
    id: 30,
    name: "Merlot",
    price: 1750,
    category: "WINE",
    image: "img/Wine/merlot.png",
    flash: false,
    discount: 50,
  },
];
